#!/bin/bash
PYTHON_SCRIPT=$1
. ~/.bashrc
conda activate climada_env


sleep_time=$((($RANDOM % 5) + 5))

echo $sleep_time

sleep $sleep_time

bsub -W 4:00 -R "rusage[mem=40000]" python3 ../python_scripts/compute_flood_degree_warming.py warming_level ''
